name: Update Submodule

on: repository_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v1
      with:
        submodules: true 
        token: ${{ secrets.TOKEN }} 
    
