name: Update Submodule

on: [repository_dispatch]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Run a one-line script
      with:
        submodules: true 
        token: ${{ secrets.TOKEN }} 
    
