name: Update Submodules

on: repository_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v1
      with:
        submodules: recursive 
        token: ${{ secrets.TOKEN }} 
    - run: |
        git config --global user.email "5744432+staceb@users.noreply.github.com"
        git config --global user.name "staceb"
        git checkout master
        git submodule update --remote --merge
        git commit -m "update submodule" 
        git push origin master
      
  
    
